spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;mode=mysql
    username: sa
    password:

  flyway:
    enabled: false

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

external-client:
  fcm: http://all-knu-fcm-develop:8080