spring:
  profiles:
    active: local # 기본적으로 local 적용
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/
      suffix: .html
  resources:
    static-locations: classpath:/static/
  web:
    resources:
      add-mappings: false


server:
  error:
    whitelabel:
      enabled: false
